class Currency {
  final String code;
  final String name;
  final String symbol;

  const Currency({
    required this.code,
    required this.name,
    required this.symbol,
  });

  static const List<Currency> currencies = [
    Currency(code: 'SGD', name: 'Singapore Dollar', symbol: 'S\$'),
    Currency(code: 'USD', name: 'US Dollar', symbol: '\$'),
    Currency(code: 'EUR', name: 'Euro', symbol: '€'),
    Currency(code: 'GBP', name: 'British Pound', symbol: '£'),
    Currency(code: 'JPY', name: 'Japanese Yen', symbol: '¥'),
    Currency(code: 'CNY', name: 'Chinese Yuan', symbol: '¥'),
    Currency(code: 'AUD', name: 'Australian Dollar', symbol: 'A\$'),
    Currency(code: 'CAD', name: 'Canadian Dollar', symbol: 'C\$'),
    Currency(code: 'CHF', name: 'Swiss Franc', symbol: 'Fr'),
    Currency(code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK\$'),
    Currency(code: 'INR', name: 'Indian Rupee', symbol: '₹'),
    Currency(code: 'KRW', name: 'South Korean Won', symbol: '₩'),
    Currency(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM'),
    Currency(code: 'THB', name: 'Thai Baht', symbol: '฿'),
    Currency(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp'),
    Currency(code: 'PHP', name: 'Philippine Peso', symbol: '₱'),
    Currency(code: 'VND', name: 'Vietnamese Dong', symbol: '₫'),
    Currency(code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ\$'),
    Currency(code: 'BRL', name: 'Brazilian Real', symbol: 'R\$'),
    Currency(code: 'MXN', name: 'Mexican Peso', symbol: '\$'),
    Currency(code: 'RUB', name: 'Russian Ruble', symbol: '₽'),
    Currency(code: 'ZAR', name: 'South African Rand', symbol: 'R'),
    Currency(code: 'TRY', name: 'Turkish Lira', symbol: '₺'),
    Currency(code: 'AED', name: 'UAE Dirham', symbol: 'د.إ'),
    Currency(code: 'SAR', name: 'Saudi Riyal', symbol: '﷼'),
    Currency(code: 'ILS', name: 'Israeli Shekel', symbol: '₪'),
    Currency(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr'),
    Currency(code: 'SEK', name: 'Swedish Krona', symbol: 'kr'),
    Currency(code: 'DKK', name: 'Danish Krone', symbol: 'kr'),
    Currency(code: 'PLN', name: 'Polish Zloty', symbol: 'zł'),
    Currency(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč'),
    Currency(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft'),
    Currency(code: 'RON', name: 'Romanian Leu', symbol: 'lei'),
    Currency(code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв'),
    Currency(code: 'HRK', name: 'Croatian Kuna', symbol: 'kn'),
    Currency(code: 'PKR', name: 'Pakistani Rupee', symbol: '₨'),
    Currency(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳'),
    Currency(code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs'),
    Currency(code: 'NPR', name: 'Nepalese Rupee', symbol: '₨'),
    Currency(code: 'EGP', name: 'Egyptian Pound', symbol: 'E£'),
    Currency(code: 'NGN', name: 'Nigerian Naira', symbol: '₦'),
    Currency(code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh'),
    Currency(code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh'),
    Currency(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh'),
    Currency(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br'),
    Currency(code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵'),
    Currency(code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA'),
    Currency(code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA'),
    Currency(code: 'ARS', name: 'Argentine Peso', symbol: '\$'),
    Currency(code: 'CLP', name: 'Chilean Peso', symbol: '\$'),
    Currency(code: 'COP', name: 'Colombian Peso', symbol: '\$'),
    Currency(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/'),
    Currency(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴'),
    Currency(code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸'),
    Currency(code: 'UZS', name: 'Uzbekistani Som', symbol: 'so\'m'),
    Currency(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د'),
    Currency(code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا'),
    Currency(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك'),
    Currency(code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.'),
    Currency(code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق'),
    Currency(code: 'BHD', name: 'Bahraini Dinar', symbol: 'د.ب'),
  ];
}
