// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZSmHezPgo7Tndj4ahw8Saf-nN10yRCUg',
    appId: '1:457646309364:android:5a5456e85cef8a062103a1',
    messagingSenderId: '457646309364',
    projectId: 'flashcardme-9beb0',
    storageBucket: 'flashcardme-9beb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi26lX7RicDXX364xyhO5qUrVJCbToZiI',
    appId: '1:457646309364:ios:56e37bd739a394f32103a1',
    messagingSenderId: '457646309364',
    projectId: 'flashcardme-9beb0',
    storageBucket: 'flashcardme-9beb0.firebasestorage.app',
    iosBundleId: 'app.settlefinance.mobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1iTCzb7vuBJeXqZGBo6ncgt4ulC5LjZo',
    appId: '1:457646309364:web:2af3388b0df9f7802103a1',
    messagingSenderId: '457646309364',
    projectId: 'flashcardme-9beb0',
    authDomain: 'flashcardme-9beb0.firebaseapp.com',
    storageBucket: 'flashcardme-9beb0.firebasestorage.app',
    measurementId: 'G-5SZHNVGZCJ',
  );

}